#cloud-config
packages:
- unzip


write_files:
# sshconf
- path: /home/prometheus/.ssh/authorized_keys
  content: |
    ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAnRMDhongUg0DarYUEAHymX5UDc8Q/jy0u78ubGInrQKNgqItd6+GVV5I43YSuww4R2sIOeNu39sEPkD0DtqRrXFIA4m8exX5f3W+bg+JVRn2WUodh2LNfOZg574sxz2cWoAavqdomSPUG/w2x4DFCy37GlR2ztaN5/1Poz4V3uXShAmXUKjYz829jhWP5/5fcOl6g/B+N2yawd4IxeJvumz+c+r3AjQYIdkr0vz8OdmHbMkPOOzoSBHxhKq0/4NgzIim1tlJZWMN2ZPQZ7sLdU05Yx3+1tnDuy4VDFn2pZj0WL18fq1arzMKLtU1dcnXEJPyqwZsNkm9oDJF5MdFQw==
    


# Prometheus config
- path: /opt/prometheus/monitor_prometheus.yml
  content: |
    rule_files:
    - 'prometheus.rules'
    scrape_configs:
    - job_name: cluster_monitoring
      scrape_interval: 10s
      consul_sd_configs:
      - server: '{{getip(variables.consul_host)}}:8500'
        datacenter: dataavenue
        services: ['lb_cluster', 'da_cluster']
      relabel_configs:
      - source_labels: ['__meta_consul_service']
        regex:         '(.*)'
        target_label:  'job'
        replacement:   '$1'
      - source_labels: ['__meta_consul_service']
        regex:         '(.*)'
        target_label:  'group'
        replacement:   '$1'

# Prometheus rules (expressions and alerts)
- path: /opt/prometheus/prometheus.rules
  content: |
    lb_cpu_utilization = 100 - (avg (rate(node_cpu{group="lb_cluster",mode="idle"}[60s])) * 100)
    da_cpu_utilization = 100 - (avg (rate(node_cpu{group="da_cluster",mode="idle"}[60s])) * 100)

    da_ram_utilization = (sum(node_memory_MemFree{job="da_cluster"}) / sum(node_memory_MemTotal{job="da_cluster"})) * 100
    lb_ram_utilization = (sum(node_memory_MemFree{job="lb_cluster"}) / sum(node_memory_MemTotal{job="lb_cluster"})) * 100

    lb_hdd_utilization = sum(node_filesystem_free{job="lb_cluster",mountpoint="/", device="rootfs"}) / sum(node_filesystem_size{job="lb_cluster",mountpoint="/", device="rootfs"}) *100
    da_hdd_utilization = sum(node_filesystem_free{job="da_cluster",mountpoint="/", device="rootfs"}) / sum(node_filesystem_size{job="da_cluster",mountpoint="/", device="rootfs"}) *100


    ALERT lb_overloaded
      IF lb_cpu_utilization > 50 OR lb_ram_utilization < 10 OR lb_hdd_utilization < 10
      FOR 1m
      LABELS {alert="overloaded", cluster="lb_cluster", node="lb", infra_id="{{infra_id}}"}
      ANNOTATIONS {
      summary = "LB cluster overloaded",
      description = "LB cluster average CPU/RAM/HDD utilization is overloaded"}
    ALERT lb_underloaded
      IF lb_cpu_utilization < 20
      FOR 2m
      LABELS {alert="underloaded", cluster="lb_cluster", node="lb", infra_id="{{infra_id}}"}
      ANNOTATIONS {
      summary = "LB cluster underloaded",
      description = "LB cluster average CPU/RAM/HDD utilization is underloaded"}
    ALERT da_overloaded
      IF da_cpu_utilization > 50 OR lb_ram_utilization < 10 OR lb_hdd_utilization < 10
      FOR 1m
      LABELS {alert="overloaded", cluster="da_cluster", node="da", infra_id="{{infra_id}}"}
      ANNOTATIONS {
      summary = "DA cluster overloaded",
      description = "DA cluster average CPU/RAM/HDD utilization is overloaded"}
    ALERT da_underloaded
      IF da_cpu_utilization < 20
      FOR 2m
      LABELS {alert="underloaded", cluster="da_cluster", node="da", infra_id="{{infra_id}}"}
      ANNOTATIONS {
      summary = "DA cluster underloaded",
      description = "DA cluster average CPU/RAM/HDD utilization is underloaded"}



# Prometheus service
- path: /etc/systemd/system/prometheus.service
  content: |
    [Unit]
    Description=prometheus service
    After=network.target

    [Service]
    Type=simple
    WorkingDirectory=/opt/prometheus
    LimitNOFILE=65536
    Environment='ALLOUT=/opt/prometheus/prometheus.log'
    EnvironmentFile=-/etc/default/prometheus
    ExecStart=/bin/sh -c "exec /opt/prometheus/prometheus -config.file /opt/prometheus/monitor_prometheus.yml > /opt/prometheus/prometheus.log -alertmanager.url=http://localhost:9093 ${PROMOTHEUS_OPTS} > ${ALLOUT} 2>&1"
    KillMode=control-group
    #Restart=always

    [Install]
    WantedBy=multi-user.target

# alertmanager service
- path: /etc/systemd/system/alertmanager.service
  content: |
    [Unit]
    Description=alertmanager service
    After=network.target

    [Service]
    Type=simple
    WorkingDirectory=/opt/prometheus
    EnvironmentFile=-/opt/prometheus
    Type=simple
    ExecStart=/opt/prometheus/alertmanager -config.file=/opt/prometheus/alertmanager.conf
    Restart=always
    [Install]
    WantedBy=multi-user.target

# prometheus executor service
- path: /etc/systemd/system/executor.service
  content: |
    [Unit]
    Description=prometheus executor
    After=network.target

    [Service]
    Type=simple
    WorkingDirectory=/opt/prometheus
    EnvironmentFile=-/opt/prometheus/prometheus_executor
    Type=simple
    ExecStart=/bin/sh -c "/opt/prometheus/prometheus_executor/executor -l 127.0.0.1:9095 /opt/prometheus/prometheus_executor/executor_conf.sh"
    Restart=always
    [Install]
    WantedBy=multi-user.target


# alertmanager
- path: /opt/prometheus/alertmanager.conf
  content: |
    global:
    
    # The root route on which each incoming alert enters.
    # The root route with all parameters, which are inherited by the child
    # routes if they are not overwritten.
    route:
      receiver: 'default'
      group_wait: 10s
      group_interval: 20s
      repeat_interval: 3m
      group_by: [cluster, alertname]
    
      routes:
      - match:
          alertname: lb_underloaded
      - receiver: default
    
    receivers:
    - name: 'default'
      webhook_configs: 
       - url: http://localhost:9095

# executor config
- path: /opt/prometheus/prometheus_executor/executor_conf.sh
  content: |
    #!/bin/bash
    
    if [[ "$AMX_STATUS" != "firing" ]]; then
      exit 0
    fi
    
    over_loaded() {
      curl -X POST http://192.168.0.4:5000/infrastructures/$1/scaleup/$2
    }
    
    under_loaded() {
      curl -X POST http://192.168.0.4:5000/infrastructures/$1/scaledown/$2
    }
    
    main() {
      for i in $(seq 1 "$AMX_ALERT_LEN"); do
        alert="AMX_ALERT_${i}_LABEL_alert"
        infra="AMX_ALERT_${i}_LABEL_infra_id"
        node="AMX_ALERT_${i}_LABEL_node"
    
        if [ "${!alert}" = "overloaded" ]
        then
            over_loaded "${!infra}" "${!node}"
        else
            under_loaded "${!infra}" "${!node}"
        fi
      done
      wait
    }

    main "$@"
#- rm -rf /opt/prometheus/prometheus-0.20.0.linux-amd64
runcmd:
- mkdir /opt/prometheus/
- mkdir /opt/prometheus/prometheus_executor
- wget "https://github.com/prometheus/prometheus/releases/download/0.20.0/prometheus-0.20.0.linux-amd64.tar.gz" -O prometheus.tar.gz
- wget "https://github.com/rabotond/szakdolgozat/raw/master/alertmanager" -O alertmanager
- wget "https://github.com/rabotond/szakdolgozat/raw/master/executor" -O executor
- chmod 777 alertmanager
- chmod 777 executor
- chmod 777 /opt/prometheus/prometheus_executor/executor_conf.sh
- mv alertmanager /opt/prometheus
- mv executor /opt/prometheus/prometheus_executor
- tar -xvzf prometheus.tar.gz -C /opt/prometheus/
- rm /opt/prometheus/prometheus-0.20.0.linux-amd64/prometheus.yml
- cp -R /opt/prometheus/prometheus-0.20.0.linux-amd64/prometheus /opt/prometheus/
- sudo systemctl enable prometheus.service
- sudo systemctl enable alertmanager.service
- sudo systemctl enable executor.service
- sudo rm -rf /opt/prometheus/data
- sudo systemctl start prometheus.service
- sudo systemctl start alertmanager.service
- sudo systemctl start executor.service
